[build]
  command = "./netlify-build.sh"
  publish = "dist"
  environment = { NODE_VERSION = "18", NETLIFY_USE_YARN = "false", NETLIFY_BUILD_BASE = "npm" }
  ignore_gemfile = true

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Explicitly ignore Jekyll/Ruby
[build.processing]
  skip_processing = true 